encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("newpage/", views.newpage, name="newpage"),
    path("editpage/", views.editpage, name="editpage"),
    path("randompage/", views.randompage, name="randompage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('wiki/', include("encyclopedia.urls")),
    path('search/', include("encyclopedia.urls")),
    path('newpage/', include("encyclopedia.urls")),
    path('editpage/', include("encyclopedia.urls")),
    path('randompage/', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.http import HttpResponseRedirect
import markdown2
import random

from . import util

# index returns an unordered list of links to all of the wiki pages


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# entry returns the html of the given page (provided with the title parameter)
# If a title is not found, the user is presented with an error


def entry(request, title):
    rawMarkdown = util.get_entry(title)
    if rawMarkdown is not None:
        html = markdown2.markdown(rawMarkdown)
        return render(request, "encyclopedia/layout.html", {
            "html": html,
            "title": title
        })
    else:
        return render(request, "encyclopedia/layout.html", {
            "title": title,
            "html": "<h1>Error! Page not found.</h1>"
        })

# search uses the request provided by the user to look for matching strings
# or substrings. If there is an exact match, the user is taken to the page.
# A matching substring returns a list of possible entries.


def search(request):
    # I referenced https://stackoverflow.com/questions/4706255/how-to-get-value-from-form-field-in-django-framework
    # to see how to grab the inputted value from the name field from the user submitted form.
    query = request.GET.get('q')
    entries = util.list_entries()
    res = []
    for entry in entries:
        if query.lower() == entry.lower():
            rawMarkdown = util.get_entry(query)
            html = markdown2.markdown(rawMarkdown)
            return render(request, "encyclopedia/layout.html", {
                "html": html,
                "title": query
            })
        if query.lower() in entry.lower():
            res.append(entry)
    if (len(res) == 0):
        return render(request, "encyclopedia/index.html", {
            "title": "Search Results",
            "html": "<h1> No matching search results. </h1>"
        })
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": res,
            "searchBool": True
        })

# newpage presents a user with a blank textarea to input markdown to create a new page
# The user first inputs a title, and if it exists, they are presented with an error. Otherwise,
# The page is saved locally and presents in the index and searches.


def newpage(request):
    if request.method == "POST":
        entries = util.list_entries()
        newPageTitle = request.POST.get('newPageTitle')
        for entry in entries:
            if newPageTitle.lower() == entry.lower():
                return render(request, "encyclopedia/layout.html", {
                    "html": "<h1>ERROR! Page already exists</h1>",
                    "title": None})
        newPageContent = request.POST.get("newPageContent")
        util.save_entry(newPageTitle, newPageContent)
        html = markdown2.markdown(newPageContent)
        return render(request, "encyclopedia/layout.html", {
            "html": html,
            "title": newPageTitle
        })

    else:
        return render(request, "encyclopedia/newpage.html")

# editpage presents the user with a pages existing markdown in a textarea that can
# be edited. If the request method is get, they are presented with the existing markdown
# If the request method is post, the new markdown is saved, overwriting the old file.


def editpage(request):

    if request.method == "POST":
        title = request.POST.get('title')
        rawMarkdown = request.POST.get('updatedPage')
        util.save_entry(title, rawMarkdown)
        html = markdown2.markdown(rawMarkdown)
        return render(request, "encyclopedia/layout.html", {
            "html": html,
            "title": title
        })
    else:
        title = request.GET.get('title')
        rawMarkdown = util.get_entry(title)
        return render(request, "encyclopedia/editpage.html", {
            "editPage": True,
            "title": title,
            "rawMarkdown": rawMarkdown,
        })

# I referenced https://www.w3schools.com/python/ref_random_choice.asp for the randchoice function.
# I referenced https://docs.djangoproject.com/en/4.2/topics/http/shortcuts/ for the redirect function

# randompage uses the random module to pick a random entry and renders the layout
# for that page.


def randompage(request):
    entries = util.list_entries()
    randTitle = random.choice(entries)
    html = markdown2.markdown(util.get_entry(randTitle))
    return render(request, "encyclopedia/layout.html", {
        "html": html,
        "title": randTitle
    })

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit Page
{% endblock %}

{% block body %}
<h2>Edit {{title}} Page</h2>
<form action="{% url 'encyclopedia:editpage' %}" method="post">
    {% csrf_token %}
    <textarea name="updatedPage">{{rawMarkdown}}</textarea>
    <input type="hidden" name="title" value="{{title}}">
    <br>
    <input type="submit" value="Submit">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
{% if searchBool is True %}
<h1>Search Results</h1>
{% else %}
<h1>All Pages</h1>
{% endif %}
<ul>
    {% for entry in entries %}
    <li>
        <a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'encyclopedia:search' %}">
                <input type="text" name="q" placeholder="Search Encyclopedia">
            </form>
            <div>
                <a href="{% url 'encyclopedia:index' %}">Home</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:randompage' %}"> Random Page </a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% if title is not None and editPage is not True %}
            <form action="{% url 'encyclopedia:editpage'%}" method="get">
                <input type="hidden" name="title" value="{{ title }}">
                <input type="submit" value="Edit Page">
            </form>
            {% endif %}
            {% block body %}
            {{ html|safe }}
            {% endblock %}
        </div>
    </div>

</body>

</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
New Page
{% endblock %}

{% block body %}
<h2>Create a New Page</h2>
<form action="{% url 'encyclopedia:newpage' %}" method="post">
    {% csrf_token %}
    <input type="text" name="newPageTitle" placeholder="Enter a Page Title">
    <br>
    <textarea id="w3review" name="newPageContent" placeholder="Use markdown to create a new page"></textarea>
    <input type="submit" value="Submit">
</form>
{% endblock %}